name: CI

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.3.app
  XCODE_DEVELOPER_DIR_PATH: /Applications/Xcode_13.3.app/Contents/Developer

jobs:
  build:
    name: build & test
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1
      - name: Build for testing
        run: |
          set -o pipefail && swift build
      - name: Test
        run: |
          set -o pipefail && swift test
