name: CI

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.5.app

jobs:
  build & test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build for testing
        run: |
          set -o pipefail && swift build
      - name: Test
        run: |
          set -o pipefail && swift test
